version: '3.8'

services:
  app:
    build: .
    container_name: solatext-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=solite
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SOLANA_NETWORK=devnet
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: solatext-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solite
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - solatext-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  solatext-data: 